### ISSUE TITLE
What are you using this for?

### ISSUE THREAD

**Issue by zeke** [mafintosh/localcast#1]
Just curious.

**Comment by mafintosh** [comment]
I'm using it to bridge node processes to static websites.

Yesterday I added a new stats interface to the next version of dat

```
npm install -g dat-next-next
dat-next-next a-file
```

In another terminal

```
dat-next-next <key-from-above> a-file --stats
```

This then runs a localcast stats emits download/upload events. I then made a static website, https://hyperdrive.technology that also runs a localcast emitter and graphs the download progress.

**Comment by zeke** [comment]
Mad science. :)
